name: ESLint

on: [push]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install --ignore-engines
      - uses: stefanoeb/eslint-action@1.0.2
        with:
          files: "{apps,libs}/"
